#include "iostream"
#include "string.h"

#include "especialidad.h"
#include "persona.h"
#include "fecha.h"
#include "informes.h"
#include "paciente.h"
#include "profesional.h"
#include "medicacion.h"
#include "planfarmacologico.h"
#include "registro.h"
#include "archivo.h"
#include "detalleplanfarmacologico.h"
